spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/railway-ticket_reservation-system
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

twilio:
  account_sid: ACad5261524e2f0e05c594ca8f384af7b7
  auth_token: e667de6bc709ac296c2b2ac6b56c2d0a
  trial_number: +

